/* 
https://www.iconfinder.com/icons/1243689/call_phone_icon
Creative Commons (Attribution 3.0 Unported);
https://www.iconfinder.com/Makoto_msk */

export const storeProducts = [
  {
    id: 1,
    title: 'Johnnie Walker Double Black',
    img: 'img/Double-Black.jpg',
    price: 4650,
    artist: 'whisky',
    info: 'Johnnie walker double black is a Scotch whisky classified as blended scotch whisky. It contains 40% ABV (alcohol by volume). It is offered in 1 litre at Ksh 5150 at Drinks Vine online liquor store. We offer you affordable prices and regular offers coupled with free delivery in Nairobi and environs. Call us, emails or WhatsApp us for reliable online liquor delivery. This smoky whisky which was inspired by the legendary JW Black Label. This family consists of the most sought after blended whiskies.',
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 2,
    title: 'Jim Beam',
    img: 'img/jim-bim.jpg',
    price: 2600,
    artist: 'whisky',
    info: 'Jim beam is a American whisky classified as american bourbon whisky. It contains 40% ABV (alcohol by volume). It is offered in 1 litre at Ksh 2600 at Drinks Vine online liquor store. We offer you affordable prices and regular offers coupled with free delivery in Nairobi and environs. Call us, emails or WhatsApp us for reliable online liquor delivery. The Jim Beam brand also offers other products like the jim beam apple (liqueur), jim beam apple, jim beam red stag, jim beam black tripple aged, jim beam honey (liqueur), jim beam honey, Jim beam double oak, Jim beam black extra aged, Jim beam signature craft, Jim Beam Devils Cut, Jim Beam Single Barrel which we are currently offering in our liquor shop.',
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 3,
    title: 'Famous Grouse',
    img: 'img/famous-grouse.jpg',
    price: 1950,
    artist: 'whisky',
    info: 'Famous grouse is a Scotch whisky classified as blended scotch whisky. It contains 40% ABV (alcohol by volume). It is offered in 750 ml at Ksh 1950, 1 litre at Ksh 2150 at Drinks Vine online liquor store. We offer you affordable prices and regular offers coupled with free delivery in Nairobi and environs. Call us, emails or WhatsApp us for reliable online liquor delivery. The Famous grouse brand also offers other products like the famous grouse king size, famous grouse smoky black, famous grouse 12 years gold reserve, The famous grouse bourbon cask, The snow grouse, Naked Grouse, The Famous Grouse Ruby Cask, famous grouse toasted cask, Famous Grouse 16 Years which we are currently offering in our liquor shop.',
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 4,
    title: 'Vat 69',
    img: 'img/vat-69.jpg',
    price: 1600,
    artist: 'whisky',
    info: 'Vat 69 is a Scotch whisky classified as blended scotch whisky. It contains 40% ABV (alcohol by volume). It is offered in 750 ml at Ksh 1600, 1 litre at Ksh 1900 at Drinks Vine online liquor store. We offer you affordable prices and regular offers coupled with free delivery in Nairobi and environs. Call us, emails or WhatsApp us for reliable online liquor delivery. This whisky was created by William Sanderson & Son Limited of South Queensferry, Scotland that was absorbed into DCL, now Diageo. The Vat 69 was introduced in the market in 1882. The name came after a panel of experts was hired to taste one hundred casks of blended whisky, and the 69th batch was judged to be the best giving the whisky a brand name. The whiskey is well blended to enhance the taste. It’s manufactured by about 40 malts and grain whiskeys being stored in smaller vats. From there it is well mixed to enhance the smooth, balanced spirit taste. It has no age statement because of the combination of malts and grains. To the nose, it has hints of spice and caramel, notes of barley malt, with a soft wheat character — a touch of pear juice. To the palate, it has ground almonds and barley malt. Slightly biscuit, more of those pear notes, a little pepper.',
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 5,
    title: '4th Street sweet rose 750 ml',
    img: 'img/4th-Street-Red.jpg',
    price: 1200,
    artist: 'wine',
    info: '4th Street sweet rose is a South African wine classified as rose wine or south african wines. It contains 7% ABV (alcohol by volume). It is offered in 750 ml at Ksh 1200, 1.5 litres at Ksh 1800 at Drinks Vine online liquor store. We offer you affordable prices and regular offers coupled with free delivery in Nairobi and environs. Call us, emails or WhatsApp us for reliable online liquor delivery. The 4th Street brand also offers other products like the 4th street rose cask, 4th street red sweet, 4th street red sweet cask, 4th street white sweet cask, 4th street white sweet which we are currently offering in our liquor shop.',
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 6,
    title: 'Jameson',
    img: 'img/jameson.jpg',
    price: 2700,
    artist: 'whisky',
    info: 'Jameson is a Irish whisky classified as irish whisky. It contains 40% ABV (alcohol by volume). It is offered in 750 ml at Ksh 2700, 1 litre at Ksh 3050, 4.5 litres at Ksh 14500 at Drinks Vine online liquor store. We offer you affordable prices and regular offers coupled with free delivery in Nairobi and environs. Call us, emails or WhatsApp us for reliable online liquor delivery. Jameson Original is made of pot still and grain whiskey that is triple distilled to create a smooth taste of vanilla and hints of sweet sherry. Jameson is aged for a minimum of 4 years to give it a floral fragrance smell. Over a span of time. This brand has increased the popularity of Jameson on international scale making it the highest selling Irish whiskey globally.',
     inCart: false,
    count: 0,
    total: 0,
  },  {
    id: 7,
    title: 'Johnnie Walker Double Black',
    img: 'img/Double-Black.jpg',
    price: 4650,
    artist: 'whisky',
    info: 'Johnnie walker double black is a Scotch whisky classified as blended scotch whisky. It contains 40% ABV (alcohol by volume). It is offered in 1 litre at Ksh 5150 at Drinks Vine online liquor store. We offer you affordable prices and regular offers coupled with free delivery in Nairobi and environs. Call us, emails or WhatsApp us for reliable online liquor delivery. This smoky whisky which was inspired by the legendary JW Black Label. This family consists of the most sought after blended whiskies.',
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 8,
    title: 'Jim Beam',
    img: 'img/jim-bim.jpg',
    price: 2600,
    artist: 'whisky',
    info: 'Jim beam is a American whisky classified as american bourbon whisky. It contains 40% ABV (alcohol by volume). It is offered in 1 litre at Ksh 2600 at Drinks Vine online liquor store. We offer you affordable prices and regular offers coupled with free delivery in Nairobi and environs. Call us, emails or WhatsApp us for reliable online liquor delivery. The Jim Beam brand also offers other products like the jim beam apple (liqueur), jim beam apple, jim beam red stag, jim beam black tripple aged, jim beam honey (liqueur), jim beam honey, Jim beam double oak, Jim beam black extra aged, Jim beam signature craft, Jim Beam Devils Cut, Jim Beam Single Barrel which we are currently offering in our liquor shop.',
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 9,
    title: 'Famous Grouse',
    img: 'img/famous-grouse.jpg',
    price: 1950,
    artist: 'whisky',
    info: 'Famous grouse is a Scotch whisky classified as blended scotch whisky. It contains 40% ABV (alcohol by volume). It is offered in 750 ml at Ksh 1950, 1 litre at Ksh 2150 at Drinks Vine online liquor store. We offer you affordable prices and regular offers coupled with free delivery in Nairobi and environs. Call us, emails or WhatsApp us for reliable online liquor delivery. The Famous grouse brand also offers other products like the famous grouse king size, famous grouse smoky black, famous grouse 12 years gold reserve, The famous grouse bourbon cask, The snow grouse, Naked Grouse, The Famous Grouse Ruby Cask, famous grouse toasted cask, Famous Grouse 16 Years which we are currently offering in our liquor shop.',
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 10,
    title: 'Vat 69',
    img: 'img/vat-69.jpg',
    price: 1600,
    artist: 'whisky',
    info: 'Vat 69 is a Scotch whisky classified as blended scotch whisky. It contains 40% ABV (alcohol by volume). It is offered in 750 ml at Ksh 1600, 1 litre at Ksh 1900 at Drinks Vine online liquor store. We offer you affordable prices and regular offers coupled with free delivery in Nairobi and environs. Call us, emails or WhatsApp us for reliable online liquor delivery. This whisky was created by William Sanderson & Son Limited of South Queensferry, Scotland that was absorbed into DCL, now Diageo. The Vat 69 was introduced in the market in 1882. The name came after a panel of experts was hired to taste one hundred casks of blended whisky, and the 69th batch was judged to be the best giving the whisky a brand name. The whiskey is well blended to enhance the taste. It’s manufactured by about 40 malts and grain whiskeys being stored in smaller vats. From there it is well mixed to enhance the smooth, balanced spirit taste. It has no age statement because of the combination of malts and grains. To the nose, it has hints of spice and caramel, notes of barley malt, with a soft wheat character — a touch of pear juice. To the palate, it has ground almonds and barley malt. Slightly biscuit, more of those pear notes, a little pepper.',
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 11,
    title: '4th Street sweet rose 750 ml',
    img: 'img/4th-Street-Red.jpg',
    price: 1200,
    artist: 'wine',
    info: '4th Street sweet rose is a South African wine classified as rose wine or south african wines. It contains 7% ABV (alcohol by volume). It is offered in 750 ml at Ksh 1200, 1.5 litres at Ksh 1800 at Drinks Vine online liquor store. We offer you affordable prices and regular offers coupled with free delivery in Nairobi and environs. Call us, emails or WhatsApp us for reliable online liquor delivery. The 4th Street brand also offers other products like the 4th street rose cask, 4th street red sweet, 4th street red sweet cask, 4th street white sweet cask, 4th street white sweet which we are currently offering in our liquor shop.',
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 12,
    title: 'Jameson',
    img: 'img/jameson.jpg',
    price: 2700,
    artist: 'whisky',
    info: 'Jameson is a Irish whisky classified as irish whisky. It contains 40% ABV (alcohol by volume). It is offered in 750 ml at Ksh 2700, 1 litre at Ksh 3050, 4.5 litres at Ksh 14500 at Drinks Vine online liquor store. We offer you affordable prices and regular offers coupled with free delivery in Nairobi and environs. Call us, emails or WhatsApp us for reliable online liquor delivery. Jameson Original is made of pot still and grain whiskey that is triple distilled to create a smooth taste of vanilla and hints of sweet sherry. Jameson is aged for a minimum of 4 years to give it a floral fragrance smell. Over a span of time. This brand has increased the popularity of Jameson on international scale making it the highest selling Irish whiskey globally.',
     inCart: false,
    count: 0,
    total: 0,
  }

]

export const detailProduct = {

    id: 1,
    title: 'Johnnie Walker Double Black',
    img: 'img/Double-Black.jpg',
    price: 4650,
    artist: 'whisky',
    info: 'Johnnie walker double black is a Scotch whisky classified as blended scotch whisky. It contains 40% ABV (alcohol by volume). It is offered in 1 litre at Ksh 5150 at Drinks Vine online liquor store. We offer you affordable prices and regular offers coupled with free delivery in Nairobi and environs. Call us, emails or WhatsApp us for reliable online liquor delivery. This smoky whisky which was inspired by the legendary JW Black Label. This family consists of the most sought after blended whiskies.',
    inCart: false,
    count: 0,
    total: 0,

}
